# Generated by Django 3.0.2 on 2021-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='Сфера деятельности')),
                ('prefix', models.CharField(blank=True, max_length=3, verbose_name='Префикс для фильтра')),
                ('slug', models.SlugField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': ' Сфера деятельности',
                'verbose_name_plural': ' Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='BeeGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=20, verbose_name='Вид работ')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название проекта')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Bee - галерея',
                'verbose_name_plural': 'Bee - галерея',
            },
        ),
        migrations.CreateModel(
            name='CoffeeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='Дата')),
                ('time', models.CharField(blank=True, max_length=50, verbose_name='Время')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Coffee - cообщение, заказ',
                'verbose_name_plural': 'Coffee - cообщения, заказы',
            },
        ),
        migrations.CreateModel(
            name='CoffeeGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название фото')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Coffee - галерея',
                'verbose_name_plural': 'Coffee - галерея',
            },
        ),
        migrations.CreateModel(
            name='CoffeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название кофейни')),
                ('about', models.CharField(blank=True, max_length=550, verbose_name='О нас')),
                ('download_menu', models.FileField(blank=True, upload_to='', verbose_name='Меню для скачивания')),
            ],
            options={
                'verbose_name': 'Coffee - info',
                'verbose_name_plural': 'Coffee - info',
            },
        ),
        migrations.CreateModel(
            name='CoffeeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название блюда')),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='Описание блюда')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Coffee - меню',
                'verbose_name_plural': 'Coffee - меню',
            },
        ),
        migrations.CreateModel(
            name='CoffeeMenu9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название блюда')),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='Описание блюда')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Coffee - меню 9',
                'verbose_name_plural': 'Coffee - меню 9',
            },
        ),
        migrations.CreateModel(
            name='CoffeePopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название блюда')),
                ('description', models.CharField(blank=True, max_length=90, verbose_name='Описание блюда')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Coffee - популярное',
                'verbose_name_plural': 'Coffee - популярное',
            },
        ),
        migrations.CreateModel(
            name='CoffeeTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото человека')),
                ('testimonial', models.CharField(blank=True, max_length=800, verbose_name='Отзыв')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия')),
                ('who_is', models.CharField(blank=True, max_length=50, verbose_name='Кто это')),
            ],
            options={
                'verbose_name': 'Coffee - отзыв',
                'verbose_name_plural': 'Coffee - отзывы',
            },
        ),
        migrations.CreateModel(
            name='ConstructoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название проекта')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Constructo - галерея',
                'verbose_name_plural': 'Constructo - галерея',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('lname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('template_number', models.CharField(blank=True, max_length=50, verbose_name='Номер шаблона')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': ' Сообщение',
                'verbose_name_plural': ' Сообщения',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAdm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('lname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('template_number', models.CharField(blank=True, max_length=50, verbose_name='Номер шаблона')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': ' Доступ в админку',
                'verbose_name_plural': ' Доступы в админку',
            },
        ),
        migrations.CreateModel(
            name='FeedbackBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('lname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('template_number', models.CharField(blank=True, max_length=50, verbose_name='Номер шаблона')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': ' Заказ',
                'verbose_name_plural': ' Заказы',
            },
        ),
        migrations.CreateModel(
            name='Funny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_foods', models.CharField(blank=True, max_length=15, verbose_name='Заказ еды')),
                ('order_phone', models.CharField(blank=True, max_length=20, verbose_name='Тел. для заказа')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный тел.')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='Е-мейл')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='Название в шапке')),
                ('head_description', models.TextField(blank=True, max_length=300, verbose_name='Описание в шапке')),
                ('download_menu', models.FileField(blank=True, upload_to='', verbose_name='Меню для скачивания')),
                ('first_title', models.CharField(blank=True, max_length=15, verbose_name='Название первого раздела')),
                ('first_text', models.CharField(blank=True, max_length=550, verbose_name='Текст первого раздела')),
                ('second_title', models.CharField(blank=True, max_length=15, verbose_name='Название второго раздела')),
                ('second_text', models.CharField(blank=True, max_length=550, verbose_name='Текст второго раздела')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Наш адрес')),
                ('work_time', models.CharField(blank=True, max_length=100, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Funny - ресторан',
                'verbose_name_plural': 'Funny - ресторан',
            },
        ),
        migrations.CreateModel(
            name='FunnyFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Funny - cообщение, заказ',
                'verbose_name_plural': 'Funny - cообщения, заказы',
            },
        ),
        migrations.CreateModel(
            name='FunnyGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название блюда')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Funny - галерея',
                'verbose_name_plural': 'Funny - галерея',
            },
        ),
        migrations.CreateModel(
            name='FunnyMenuFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название меню')),
                ('food', models.CharField(blank=True, max_length=40, verbose_name='Название блюда')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Funny - меню N1',
                'verbose_name_plural': 'Funny - меню N1',
            },
        ),
        migrations.CreateModel(
            name='FunnyMenuSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название меню')),
                ('food', models.CharField(blank=True, max_length=40, verbose_name='Название блюда')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Funny  - меню N2',
                'verbose_name_plural': 'Funny  - меню N2',
            },
        ),
        migrations.CreateModel(
            name='FunnyMenuThird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название меню')),
                ('food', models.CharField(blank=True, max_length=40, verbose_name='Название блюда')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Funny  - меню N3',
                'verbose_name_plural': 'Funny  - меню N3',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='', verbose_name='Логотип')),
                ('fon', models.FileField(blank=True, upload_to='', verbose_name='Фон')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=30, verbose_name='Подзаголовок')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('slide', models.FileField(blank=True, upload_to='', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': ' Образец сайта',
                'verbose_name_plural': ' Образцы сайтов',
            },
        ),
        migrations.CreateModel(
            name='KusinaAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название раздела, 25 зн.')),
                ('title', models.CharField(blank=True, max_length=25, verbose_name='Заголовок, 25 зн.')),
                ('description', models.CharField(blank=True, max_length=450, verbose_name='Описание, 450 зн.')),
                ('video_preview', models.FileField(blank=True, upload_to='', verbose_name='Превью видео, 800*1200')),
                ('video_link', models.CharField(blank=True, max_length=200, verbose_name='Код видео на Ютубе')),
                ('subtitle', models.CharField(blank=True, max_length=30, verbose_name='Подзаголовок для фото, 30 зн.')),
                ('img_1', models.FileField(blank=True, upload_to='', verbose_name='1-я картинка 800*600')),
                ('descr_1', models.CharField(blank=True, max_length=20, verbose_name='Текст под 1-й картинкой, 20 зн.')),
                ('img_2', models.FileField(blank=True, upload_to='', verbose_name='2-я картинка 800*600')),
                ('descr_2', models.CharField(blank=True, max_length=20, verbose_name='Текст под 2-й картинкой, 20 зн.')),
                ('img_3', models.FileField(blank=True, upload_to='', verbose_name='3-я картинка 800*600')),
                ('descr_3', models.CharField(blank=True, max_length=20, verbose_name='Текст под 3-й картинкой, 20 зн.')),
            ],
            options={
                'verbose_name': 'Kusina - О ресторане',
                'verbose_name_plural': 'Kusina - О ресторане',
            },
        ),
        migrations.CreateModel(
            name='KusinaDownloadMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('menu', models.FileField(blank=True, upload_to='', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Kusina - Меню для скачивания',
                'verbose_name_plural': 'Kusina - Меню для скачивания',
            },
        ),
        migrations.CreateModel(
            name='KusinaInsta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название фото')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото, 800*800')),
            ],
            options={
                'verbose_name': 'Kusina - Инстаграмм',
                'verbose_name_plural': 'Kusina - Инстаграмм',
            },
        ),
        migrations.CreateModel(
            name='KusinaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название блюда')),
                ('contents_1', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 1, 20 зн.')),
                ('contents_2', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 2, 20 зн.')),
                ('contents_3', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 3, 20 зн.')),
                ('contents_4', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 4, 20 зн.')),
                ('price', models.CharField(blank=True, max_length=10, verbose_name='Цена')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Вид блюда, 800*800')),
            ],
            options={
                'verbose_name': 'Kusina - Меню',
                'verbose_name_plural': 'Kusina - Меню',
            },
        ),
        migrations.CreateModel(
            name='KusinaNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Kusina - Рассылка',
                'verbose_name_plural': 'Kusina - Рассылка',
            },
        ),
        migrations.CreateModel(
            name='KusinaReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='Дата')),
                ('time', models.CharField(blank=True, max_length=50, verbose_name='Время')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('person', models.TextField(blank=True, verbose_name='Персон')),
            ],
            options={
                'verbose_name': 'Kusina - Бронирование',
                'verbose_name_plural': 'Kusina - Бронирования',
            },
        ),
        migrations.CreateModel(
            name='KusinaStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название раздела, 30 зн.')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фон, 1500*1000')),
                ('p_1_name', models.CharField(blank=True, max_length=30, verbose_name='Параметр 1, 30 зн.')),
                ('p_1_value', models.CharField(blank=True, max_length=5, verbose_name='Значение 1-го параметра, 5 зн.')),
                ('p_2_name', models.CharField(blank=True, max_length=30, verbose_name='Параметр 2, 30 зн.')),
                ('p_2_value', models.CharField(blank=True, max_length=5, verbose_name='Значение 2-го параметра, 5 зн.')),
                ('p_3_name', models.CharField(blank=True, max_length=30, verbose_name='Параметр 3, 30 зн.')),
                ('p_3_value', models.CharField(blank=True, max_length=5, verbose_name='Значение 3-го параметра, 5 зн.')),
                ('p_4_name', models.CharField(blank=True, max_length=30, verbose_name='Параметр 4, 30 зн.')),
                ('p_4_value', models.CharField(blank=True, max_length=5, verbose_name='Значение 4-го параметра, 5 зн.')),
            ],
            options={
                'verbose_name': 'Kusina - Статистика',
                'verbose_name_plural': 'Kusina - Статитстика',
            },
        ),
        migrations.CreateModel(
            name='KusinaTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, upload_to='', verbose_name='Фото, 800*900')),
                ('person', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия, 50 зн.')),
                ('who_is', models.CharField(blank=True, max_length=30, verbose_name='Должность, 30 зн.')),
            ],
            options={
                'verbose_name': 'Kusina - Сотрудник',
                'verbose_name_plural': 'Kusina - Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='KusinaTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.CharField(blank=True, max_length=800, verbose_name='Отзыв, 800 зн.')),
                ('photo', models.FileField(blank=True, upload_to='', verbose_name='Фото человека, 400*400')),
                ('person', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия, 50 зн.')),
                ('who_is', models.CharField(blank=True, max_length=50, verbose_name='Кто это, 50 зн.')),
            ],
            options={
                'verbose_name': 'Kusina - Отзыв',
                'verbose_name_plural': 'Kusina - Отзывы',
            },
        ),
        migrations.CreateModel(
            name='KusinaTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, verbose_name='Название ресторана, 15 зн.')),
                ('title', models.CharField(blank=True, max_length=25, verbose_name='Заголовок, 25 зн.')),
                ('subtitle', models.CharField(blank=True, max_length=125, verbose_name='Подзаголовок, 125 зн.')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Картинка слайдера 1000*1300')),
                ('img_1', models.FileField(blank=True, upload_to='', verbose_name='1-я картинка под заголовком 800*800')),
                ('descr_1', models.CharField(blank=True, max_length=25, verbose_name='Текст под 1-й картинкой, 25 зн.')),
                ('img_2', models.FileField(blank=True, upload_to='', verbose_name='2-я картинка под заголовком 800*800')),
                ('descr_2', models.CharField(blank=True, max_length=25, verbose_name='Текст под 2-й картинкой, 25 зн.')),
                ('img_3', models.FileField(blank=True, upload_to='', verbose_name='3-я картинка под заголовком 800*800')),
                ('descr_3', models.CharField(blank=True, max_length=25, verbose_name='Текст под 3-й картинкой, 25 зн.')),
            ],
            options={
                'verbose_name': 'Kusina - Верхний блок (слайд)',
                'verbose_name_plural': 'Kusina - Верхний блок (слайды)',
            },
        ),
        migrations.CreateModel(
            name='PizzaFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Pizza - cообщение, заказ',
                'verbose_name_plural': 'Pizza - cообщения, заказы',
            },
        ),
        migrations.CreateModel(
            name='PizzaGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название фото')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Pizza - галерея',
                'verbose_name_plural': 'Pizza - галерея',
            },
        ),
        migrations.CreateModel(
            name='PizzaImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название картинки')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Pizza - изображение',
                'verbose_name_plural': 'Pizza - изображения',
            },
        ),
        migrations.CreateModel(
            name='PizzaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название ресторана')),
                ('about', models.CharField(blank=True, max_length=500, verbose_name='О нас')),
                ('download_menu', models.FileField(blank=True, upload_to='', verbose_name='Меню для скачивания')),
            ],
            options={
                'verbose_name': 'Pizza - info',
                'verbose_name_plural': 'Pizza - info',
            },
        ),
        migrations.CreateModel(
            name='PizzaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название блюда')),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='Описание блюда')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Pizza - меню',
                'verbose_name_plural': 'Pizza - меню',
            },
        ),
        migrations.CreateModel(
            name='PizzaMenu12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название блюда')),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='Описание блюда')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Pizza - меню 12',
                'verbose_name_plural': 'Pizza - меню 12',
            },
        ),
        migrations.CreateModel(
            name='PizzaPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя, фамилия')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Должность')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='О человеке')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Pizza - персонал',
                'verbose_name_plural': 'Pizza - персонал',
            },
        ),
        migrations.CreateModel(
            name='PizzaPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название блюда')),
                ('description', models.CharField(blank=True, max_length=90, verbose_name='Описание блюда')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
                ('price', models.CharField(blank=True, max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Pizza - хит продаж',
                'verbose_name_plural': 'Pizza - хиты продаж',
            },
        ),
        migrations.CreateModel(
            name='TmpGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=20, verbose_name='Префикс шаблона (отрасль)')),
                ('url_name', models.CharField(blank=True, max_length=20, verbose_name='name шаблона (для ссылки)')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название шаблона')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото шаблона')),
            ],
            options={
                'verbose_name': 'Галерея шаблонов',
                'verbose_name_plural': 'Галерея шаблонов',
            },
        ),
        migrations.CreateModel(
            name='Tmpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title страницы')),
                ('title_short', models.CharField(blank=True, max_length=15, verbose_name='Заголовок в шапке')),
                ('title_crumb', models.CharField(blank=True, max_length=20, verbose_name='Название в крошках')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение 555*605')),
                ('image_cat', models.FileField(blank=True, upload_to='', verbose_name='Изображение 640*420')),
                ('caption', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для картинки')),
                ('description_short', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание шаблона')),
                ('description_long', models.CharField(blank=True, max_length=2000, verbose_name='Краткое описание шаблона')),
                ('price', models.CharField(blank=True, max_length=20, verbose_name='Цена')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': ' Шаблон',
                'verbose_name_plural': ' Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='VenueFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('massage', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Venue - cообщение, заказ',
                'verbose_name_plural': 'Venue - cообщения, заказы',
            },
        ),
        migrations.CreateModel(
            name='VenueHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, max_length=30, verbose_name='Слоган раздела')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Название раздела')),
                ('name', models.CharField(blank=True, max_length=90, verbose_name='Название блюда')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
                ('contents_1', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 1')),
                ('contents_2', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 2')),
                ('contents_3', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 3')),
                ('contents_4', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 4')),
                ('price', models.CharField(blank=True, max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Venue - хит продаж',
                'verbose_name_plural': 'Venue - хит продаж',
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Фото')),
                ('top_fon_image', models.FileField(blank=True, upload_to='', verbose_name='Верхнее фоновое фото')),
                ('first_image_section_1', models.FileField(blank=True, upload_to='', verbose_name='Первое фото первого раздела')),
                ('second_image_section_1', models.FileField(blank=True, upload_to='', verbose_name='Второе фото первого раздела')),
                ('video_name', models.CharField(blank=True, max_length=100, verbose_name='Название видео')),
                ('video_preview', models.FileField(blank=True, upload_to='', verbose_name='Превью видео')),
                ('video_link', models.CharField(blank=True, max_length=200, verbose_name='Код видео на Ютубе')),
                ('img_1', models.FileField(blank=True, upload_to='', verbose_name='Фото для Закусок')),
                ('img_2', models.FileField(blank=True, upload_to='', verbose_name='Фото для Горячего')),
                ('img_3', models.FileField(blank=True, upload_to='', verbose_name='Фото для Десертов')),
                ('bottom_fon_image', models.FileField(blank=True, upload_to='', verbose_name='Фото раздела Заказ столика')),
            ],
            options={
                'verbose_name': 'Venue - картинки',
                'verbose_name_plural': 'Venue - картинки',
            },
        ),
        migrations.CreateModel(
            name='VenueMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название блюда')),
                ('contents_1', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 1')),
                ('contents_2', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 2')),
                ('contents_3', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 3')),
                ('contents_4', models.CharField(blank=True, max_length=20, verbose_name='Ингредиент 4')),
                ('price', models.CharField(blank=True, max_length=10, verbose_name='Цена')),
                ('sign_img', models.FileField(blank=True, upload_to='', verbose_name='Вид блюда')),
            ],
            options={
                'verbose_name': 'Venue - меню',
                'verbose_name_plural': 'Venue - меню',
            },
        ),
        migrations.CreateModel(
            name='VenueRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='Дата, время')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Сколько персон')),
            ],
            options={
                'verbose_name': 'Venue - бронирование',
                'verbose_name_plural': 'Venue - бронирование',
            },
        ),
        migrations.CreateModel(
            name='VenueTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, max_length=20, verbose_name='Слоган раздела')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Заголовок раздела')),
                ('team_intro_1', models.CharField(blank=True, max_length=800, verbose_name='Текст о команде 1')),
                ('team_intro_2', models.CharField(blank=True, max_length=800, verbose_name='Текст о команде 2')),
                ('img_1', models.FileField(blank=True, upload_to='', verbose_name='Фото сотрудника 1')),
                ('name_1', models.CharField(blank=True, max_length=50, verbose_name='Имя сотрудника 1')),
                ('post_1', models.CharField(blank=True, max_length=30, verbose_name='Должность сотрудника 1')),
                ('img_2', models.FileField(blank=True, upload_to='', verbose_name='Фото сотрудника 2')),
                ('name_2', models.CharField(blank=True, max_length=50, verbose_name='Имя сотрудника 2')),
                ('post_2', models.CharField(blank=True, max_length=30, verbose_name='Должность сотрудника 2')),
                ('img_3', models.FileField(blank=True, upload_to='', verbose_name='Фото сотрудника 3')),
                ('name_3', models.CharField(blank=True, max_length=50, verbose_name='Имя сотрудника 3')),
                ('post_3', models.CharField(blank=True, max_length=30, verbose_name='Должность сотрудника 3')),
                ('img_4', models.FileField(blank=True, upload_to='', verbose_name='Фото сотрудника 4')),
                ('name_4', models.CharField(blank=True, max_length=50, verbose_name='Имя сотрудника 4')),
                ('post_4', models.CharField(blank=True, max_length=30, verbose_name='Должность сотрудника 4')),
            ],
            options={
                'verbose_name': 'Venue - команда',
                'verbose_name_plural': 'Venue - команда',
            },
        ),
        migrations.CreateModel(
            name='VenueTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, max_length=20, verbose_name='Слоган раздела')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Заголовок раздела')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фон отзывов')),
                ('testimonial', models.CharField(blank=True, max_length=800, verbose_name='Отзыв')),
                ('person', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия')),
                ('who_is', models.CharField(blank=True, max_length=50, verbose_name='Кто это')),
            ],
            options={
                'verbose_name': 'Venue - отзыв',
                'verbose_name_plural': 'Venue - отзывы',
            },
        ),
        migrations.CreateModel(
            name='VenueText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Title')),
                ('reservation_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон бронирования')),
                ('download_menu', models.FileField(blank=True, upload_to='', verbose_name='Меню для скачивания')),
                ('first_title', models.CharField(blank=True, max_length=30, verbose_name='Первая фраза на картинке')),
                ('second_title', models.CharField(blank=True, max_length=50, verbose_name='Вторая фраза на картинке')),
                ('third_title', models.CharField(blank=True, max_length=200, verbose_name='Третья фраза на картинке')),
                ('first_text_section_1', models.CharField(blank=True, max_length=50, verbose_name='Слоган первого раздела')),
                ('second_text_section_1', models.CharField(blank=True, max_length=50, verbose_name='Заголовок первого раздела')),
                ('third_text_section_1', models.CharField(blank=True, max_length=400, verbose_name='Текст первого раздела')),
                ('first_text_section_2', models.CharField(blank=True, max_length=50, verbose_name='Слоган второго раздела')),
                ('second_text_section_2', models.CharField(blank=True, max_length=50, verbose_name='Заголовок второго раздела')),
                ('menu_slogan', models.CharField(blank=True, max_length=30, verbose_name='Слоган меню')),
                ('menu_name', models.CharField(blank=True, max_length=50, verbose_name='Заголовок меню')),
                ('menu_intro_1', models.CharField(blank=True, max_length=800, verbose_name='Вступительный текст 1')),
                ('menu_intro_2', models.CharField(blank=True, max_length=800, verbose_name='Вступительный текст 2')),
                ('sign_menu_slogan', models.CharField(blank=True, max_length=30, verbose_name='Слоган фирм. меню')),
                ('sign_menu_name', models.CharField(blank=True, max_length=50, verbose_name='Заголовок фирм. меню')),
                ('footer_text', models.CharField(blank=True, max_length=400, verbose_name='Текст внизу')),
                ('footer_address', models.CharField(blank=True, max_length=100, verbose_name='Адрес внизу')),
                ('footer_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон внизу')),
                ('footer_email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл внизу')),
            ],
            options={
                'verbose_name': 'Venue - тексты',
                'verbose_name_plural': 'Venue - тексты',
            },
        ),
        migrations.CreateModel(
            name='VenueThanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=100, verbose_name='Фраза после отправки формы')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фоновое фото')),
            ],
            options={
                'verbose_name': 'Venue - форма отправлена',
                'verbose_name_plural': 'Venue - форма отправлена',
            },
        ),
    ]
