# Generated by Django 3.0.2 on 2021-03-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Tmpl',
        ),
    ]
