# Generated by Django 3.0.2 on 2021-09-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20210921_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='slug',
            new_name='area_slug',
        ),
    ]
