# Generated by Django 3.0.2 on 2021-03-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20210301_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=30, verbose_name='Сфера деятельности')),
                ('prefix', models.CharField(blank=True, max_length=3, verbose_name='Префикс для фильтра')),
                ('slug', models.SlugField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': ' Сфера деятельности',
                'verbose_name_plural': ' Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='Tmpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title страницы')),
                ('title_short', models.CharField(blank=True, max_length=15, verbose_name='Заголовок в шапке')),
                ('title_crumb', models.CharField(blank=True, max_length=20, verbose_name='Название в крошках')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение 555*605')),
                ('image_cat', models.FileField(blank=True, upload_to='', verbose_name='Изображение 640*420')),
                ('caption', models.CharField(blank=True, max_length=50, verbose_name='Заголовок для картинки')),
                ('description_short', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание шаблона')),
                ('description_long', models.CharField(blank=True, max_length=2000, verbose_name='Краткое описание шаблона')),
                ('price', models.CharField(blank=True, max_length=20, verbose_name='Цена')),
                ('slug', models.SlugField(unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Area')),
            ],
            options={
                'verbose_name': ' Шаблон',
                'verbose_name_plural': ' Шаблоны',
            },
        ),
    ]
