# Generated by Django 3.0.2 on 2021-04-02 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_area_tmpl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpl',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
