# Generated by Django 3.0.2 on 2021-09-22 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20210922_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_slug',
            new_name='slug',
        ),
        migrations.CreateModel(
            name='Tmpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title страницы')),
                ('title_short', models.CharField(max_length=15, verbose_name='Заголовок в шапке')),
                ('title_crumb', models.CharField(max_length=20, verbose_name='Название в крошках')),
                ('image', models.FileField(upload_to='images/templates/500_545', verbose_name='Изображение 500*545')),
                ('image_cat', models.FileField(upload_to='images/templates/640_420', verbose_name='Изображение 640*420')),
                ('caption', models.CharField(max_length=50, verbose_name='Заголовок для картинки')),
                ('description_short', models.CharField(max_length=500, verbose_name='Краткое описание шаблона')),
                ('description_long', models.CharField(max_length=2000, verbose_name='Подробное описание шаблона')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('tmpl_name', models.CharField(blank=True, max_length=20, verbose_name='Name шаблона в УРЛ')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Area')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['-created_date'],
            },
        ),
    ]
