# Generated by Django 3.0.2 on 2021-04-02 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_tmpl_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpl',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
