# Generated by Django 3.0.2 on 2021-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20210402_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmpl',
            options={'ordering': ['-created_date'], 'verbose_name': ' Шаблон', 'verbose_name_plural': ' Шаблоны'},
        ),
        migrations.AddField(
            model_name='tmpl',
            name='tmpl_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name шаблона'),
        ),
        migrations.AlterField(
            model_name='tmpl',
            name='description_long',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Подробное описание шаблона'),
        ),
    ]
