# Generated by Django 3.0.2 on 2021-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_auto_20210413_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Тема')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': ' Сообщение',
                'verbose_name_plural': ' Сообщения',
            },
        ),
    ]
