# Generated by Django 3.0.2 on 2021-09-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='massage',
            new_name='message',
        ),
    ]
