# Generated by Django 3.0.2 on 2021-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_auto_20210425_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Заголовок для фото')),
                ('description', models.CharField(blank=True, max_length=20, verbose_name='Описание для фото')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Bus - галерея',
                'verbose_name_plural': 'Bus - галерея',
            },
        ),
        migrations.AlterModelOptions(
            name='bushead',
            options={'verbose_name': 'Bus - верхняя часть с фото', 'verbose_name_plural': 'Bus - верхняя часть с фото'},
        ),
    ]
