# Generated by Django 3.0.2 on 2021-04-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_auto_20210425_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busgallery',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание для фото'),
        ),
    ]
