# Generated by Django 3.0.2 on 2021-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_auto_20210927_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
