# Generated by Django 3.0.2 on 2021-12-12 05:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_contactform_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title страницы')),
                ('title_short', models.CharField(max_length=15, verbose_name='Заголовок в шапке')),
                ('title_crumb', models.CharField(max_length=20, verbose_name='Название в крошках')),
                ('image', models.FileField(upload_to='images/templates/500_545', verbose_name='Скриншот')),
                ('caption', models.CharField(max_length=50, verbose_name='Заголовок для картинки')),
                ('description_short', models.CharField(max_length=500, verbose_name='Краткое описание шаблона')),
                ('description_long', models.CharField(max_length=2000, verbose_name='Подробное описание шаблона')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('tmpl_name', models.CharField(blank=True, max_length=20, verbose_name='Name шаблона в УРЛ')),
                ('is_activated', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Area')),
            ],
            options={
                'verbose_name': 'Образец в портфолио',
                'verbose_name_plural': 'Образцы в портфолио',
                'ordering': ['-created_date'],
            },
        ),
    ]
