# Generated by Django 3.0.2 on 2021-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_auto_20210425_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
    ]
