# Generated by Django 3.0.2 on 2021-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_auto_20210425_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Title страницы')),
                ('title_on_image', models.CharField(blank=True, max_length=50, verbose_name='Заголовок на главном фото')),
                ('logo', models.CharField(blank=True, max_length=30, verbose_name='Лого')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Transporters - верхняя часть с фото',
                'verbose_name_plural': 'Transporters - верхняя часть с фото',
            },
        ),
        migrations.AlterField(
            model_name='tmpl',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение 500*545'),
        ),
        migrations.AlterField(
            model_name='tmpl',
            name='tmpl_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name шаблона в УРЛ'),
        ),
    ]
