# Generated by Django 3.0.2 on 2021-12-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_auto_20211212_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmpl',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Tmpl',
        ),
    ]
