# Generated by Django 3.0.2 on 2021-12-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_auto_20211212_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_cost', models.CharField(blank=True, max_length=50, verbose_name='Цена на создание лендинга')),
                ('site_cost', models.CharField(blank=True, max_length=50, verbose_name='Цена на создание сайта')),
                ('support_cost', models.CharField(blank=True, max_length=50, verbose_name='Цена на сопровождение')),
            ],
            options={
                'verbose_name': 'Цены на услуги',
                'verbose_name_plural': 'Цены на услуги',
            },
        ),
        migrations.AlterField(
            model_name='example',
            name='example_url',
            field=models.CharField(blank=True, max_length=50, verbose_name='УРЛ сайта'),
        ),
    ]
