# Generated by Django 3.0.2 on 2021-12-14 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_auto_20211214_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title страницы')),
                ('title_short', models.CharField(max_length=30, verbose_name='Заголовок в шапке (образец сайта, пример сайта и тп}')),
                ('title_crumb', models.CharField(max_length=20, verbose_name='Название в крошках')),
                ('image', models.FileField(upload_to='images/templates/500_545', verbose_name='Скриншот')),
                ('caption', models.CharField(max_length=50, verbose_name='Заголовок для картинки')),
                ('description_short', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('description_long', models.CharField(max_length=2000, verbose_name='Подробное описание')),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('example_url', models.CharField(blank=True, max_length=50, verbose_name='УРЛ сайта')),
                ('is_activated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Образец в портфолио',
                'verbose_name_plural': 'Образцы в портфолио',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ExampleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title страницы')),
                ('title_short', models.CharField(max_length=30, verbose_name='Заголовок в шапке')),
                ('title_crumb', models.CharField(max_length=20, verbose_name='Название в крошках')),
                ('intro_title', models.CharField(max_length=50, verbose_name='Заголовок вводной части')),
                ('intro_text', models.CharField(max_length=500, verbose_name='Текст вводной части')),
                ('ps_title', models.CharField(max_length=50, verbose_name='Заголовок после фото')),
                ('ps_text', models.CharField(max_length=1500, verbose_name='Текст после фото')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
