# Generated by Django 3.0.2 on 2021-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_auto_20211214_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplelist',
            name='intro_text',
            field=models.CharField(max_length=2000, verbose_name='Текст вводной части'),
        ),
        migrations.AlterField(
            model_name='examplelist',
            name='ps_text',
            field=models.CharField(max_length=3000, verbose_name='Текст после фото'),
        ),
        migrations.AlterField(
            model_name='examplelist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title страницы'),
        ),
    ]
