# Generated by Django 3.0.2 on 2021-12-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_auto_20211214_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampledetail',
            name='caption',
            field=models.CharField(max_length=70, verbose_name='Заголовок для картинки'),
        ),
        migrations.AlterField(
            model_name='exampledetail',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='exampledetail',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title страницы'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5, verbose_name='Заголовок "Отзыв"')),
                ('testimonial', models.CharField(max_length=2000, verbose_name='Отзыв')),
                ('example_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.ExampleDetail')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
