# Generated by Django 3.0.2 on 2021-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_auto_20211218_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampledetail',
            name='testimonial_title',
            field=models.CharField(blank=True, max_length=20, verbose_name='Заголовок "Отзыв заказчика" (если есть)'),
        ),
    ]
