# Generated by Django 3.0.2 on 2021-12-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_exampledetail_testimonial_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampledetail',
            name='testimonial_title',
        ),
    ]
