# Generated by Django 3.0.2 on 2021-12-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0023_remove_exampledetail_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledetail',
            name='hosting',
            field=models.CharField(blank=True, max_length=50, verbose_name='Хостинг'),
        ),
    ]
