# Generated by Django 3.2.7 on 2022-11-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0026_auto_20211220_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exampledetail',
            name='hosting',
            field=models.CharField(blank=True, max_length=50, verbose_name='Хостинг без "/" в конце'),
        ),
        migrations.AlterField(
            model_name='exampledetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examplelist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
